
[install]
hoist = [
  "@react-native/*",
  "@react-native-community/*", 
  "react-native",
  "react",
  "metro*",
  "semver"
]

nohoist = [
  "**/react-native/node_modules/**",
  "**/react-native-*/node_modules/**"
]

[install.cache]
# Cache dependencies
